apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "chart.name" . }}
  name: {{ include "chart.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
          - name: ENV_NAME
            value: {{ .Values.namespace }}
        ports:
        - containerPort: 8080
          protocol: TCP
